name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
    
    - name: Run command lines
      run: |
          npm install
          git config user.email "junwang2003@gmail.com"
          git config user.name "edenprairie"
          npm run deploy
      
    # - name: Build and Deploy
    #  uses: JamesIves/github-pages-deploy-action@releases/v3
    #  with:
    #    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
    #    BRANCH: gh-pages # The branch the action should deploy to.
    #    FOLDER: static # The folder the action should deploy.
